### ISSUE TITLE
Dataset Problem

### ISSUE THREAD

**Issue by LarkLeeOnePiece** [facebookresearch/AnimalAvatar#5]
Can you publish the preprocessed dataset?

**Comment by RemySabathier** [comment]
Hey,
* if you mean the CSE maps and root pose, you can compute them using the preprocessing method (please follow: https://github.com/facebookresearch/AnimalAvatar#1--preprocessing)
* if you mean the additional external inputs that we provide for some scenes of Cop3D, you can find the link to external_data/ here: https://github.com/facebookresearch/AnimalAvatar#installation .

**Comment by DevikalyanDas** [comment]
Hello @RemySabathier , Thanks for your nice work. I wanted to know how you obtained the refined masks in the external data as the original COP3D masks are not good enough.

**Comment by RemySabathier** [comment]
Hi @DevikalyanDas, unfortunately the code we use to refine CoP3D masks is not publicly released yet.

**Comment by yosun** [comment]
hi! i'm at ECCV with https://instagram.com/corgi.cam

when will the masks and full data set be released so that we can extract animal avatars from many TBs of corgi videos? 

also, do let us know if you need photogenic corgi videos such as this one and beyond~! https://share.icloud.com/photos/07as9VQ5tay0e7uVUMIHqJQaQ 

collaborate directly with corgi to get a corgös number of 1 !
